"""This module is used to define the success and error messages."""
class InfoMessage:
    """
    A class to store and retrieve information messages.
    """
    userCreated = "User created successfully!"
    userUpdated = "User updated successfully!"
    userDeleted = "User deleted successfully!"
    userListRetrieved = "Successfully retrieved the list of users!"
    loginSuccess = "Login successful!"
    logoutSuccess = "Logout successful!"
    passwordChanged = "Password changed successfully!"
    verificationSent = "Verification email sent successfully!"
    operationCompleted = "Operation completed successfully!"
    fileUploaded = "File uploaded successfully!"
    emailAlreadyExists = "Email already exists!"
    userAlreadyExists = "User already exists with this email!"
    userNotExists = "User does not exist!"
    userNotFound = "User does not exist with the provided email!"
    otpSent = "OTP sent successfully!"
    userSignupSuccess = "User signed up successfully!"
    resetPasswordSuccess = "Password reset successfully!"
    otpVerified = "OTP verified successfully!"
    userRetrievedSuccess = "User information retrieved successfully!"


class ErrorMessage:
    """This class represents a user error message."""
    errorCreatingUser = "Error occurred while creating the user!"
    errorRetrievingUserList = "No user list found to retrieve!"
    errorLoginFailed = "Invalid username or password!"
    errorUnauthorized = "Unauthorized access!"
    pwdNotMatch = "Password do not match!"
    errorPasswordReset = "Error occurred while resetting the password!"
    errorFileUpload = "Error occurred while uploading the file!"
    invalidOtp = "Invalid OTP!"
    otpVerificationFailed = "OTP verification failed!"
    otpSendFailed = "Error sending OTP to user!"
    genericError = "Generic error occurred!"
    expiredToken = "Invalid or expired token!"
    userNotFound = "User not found!"
    somethingWentWrong = "Woops, something's not quite right, please try again!"
    driverSignupFailed = "Driver signup failed!"
    internalServerErr = "An internal server error occurred!"
    invalidCred = "An invalid credentials were provided!"
    generalTryAgain = "Something went wrong. Please try again!"
    emailAllreadyExists = "Email address already exists!"
    otpExpired = "OTP has expired!"
    userNotVerifiedOrFound = "User has not been verified or not found!"
    errorSavingUser = "Error occurred while saving the user!"
    invalidImageType = "Invalid image type!"
    otpGenerationFailed = "Error occurred while generating OTP!"
    errGeneratingRes = "Error occurred while generating the response!"

