"""This module is used to define the success and error messages."""
class InfoMessage:
    """
    A class to store and retrieve information messages.
    """
    userCreated = "User created successfully!"
    userUpdated = "User updated successfully!"
    userDeleted = "User deleted successfully!"
    userListRetrieved = "Successfully retrieved the list of users!"
    loginSuccess = "Login successful!"
    logoutSuccess = "Logout successful!"
    passwordChanged = "Password changed successfully!"
    verificationSent = "Verification email sent successfully!"
    operationCompleted = "Operation completed successfully!"
    fileUploaded = "File uploaded successfully!"
    emailAlreadyExists = "Email already exists!"
    userAlreadyExists = "User already exists with this email!"
    userNotExists = "User does not exist!"
    userNotFound = "User does not exist with the provided email!"
    otpSent = "OTP sent successfully!"
    userSignupSuccess = "User signed up successfully!"
    resetPasswordSuccess = "Password reset successfully!"
    otpVerified = "OTP verified successfully!"
    userRetrievedSuccess = "User information retrieved successfully!"
    driverVehicleCreatedSuccess = "Driver vehicle details are created successfully!"
    imageUploadSuccess = "Image uploaded successfully!"
    otpGenerationSuccess = "OTP generated successfully!"
    driverVehicleDocsUploadedSuccess = "Driver vehicle documents uploaded successfully!"
    passwordChangedSuccess = "Password changed successfully!"
    planSelectedSuccess = "Plan selected successfully!"
    driverStatusUpdated = "Driver status updated successfully!"
    plansChecked  = "Plans checked successfully!"
    noPlansExpired = "No plans have expired for the driver!"
    notificationSentToDrivers = "Notification sent to drivers successfully!"
    rideBookedSuccessfully = "Ride booked successfully!"
    rideRequestSent = "Ride request sent. Waiting for driver acceptance..."
    rideAcceptedSuccessfully = "Ride accepted successfully!"
    driverHeading = "Driver is heading to your location."
    reqAccepted = "Request is accepted by the driver."
    driverArrived = "Driver has arrived to your location."
    arrivedNow = "Arrived now."
    rideAndDriverFound = "Ride and driver found successfully!"
    driverReachedSuccessfully = "Driver has reached your location successfully!"
    driverTrackingSuccess = "Driver tracking information retrieved successfully!"
    rideCancelledSuccessfully = "Ride cancelled successfully!"
    numberChanged = "Number changed successfully!"

class ErrorMessage:
    """This class represents a user error message."""
    errorCreatingUser = "Error occurred while creating the user!"
    errorRetrievingUserList = "No user list found to retrieve!"
    errorLoginFailed = "Invalid username or password!"
    errorUnauthorized = "Unauthorized access!"
    pwdNotMatch = "Password do not match!"
    errorPasswordReset = "Error occurred while resetting the password!"
    errorFileUpload = "Error occurred while uploading the file!"
    invalidOtp = "Invalid OTP!"
    otpVerificationFailed = "OTP verification failed!"
    otpSendFailed = "Error sending OTP to user!"
    genericError = "Generic error occurred!"
    expiredToken = "Invalid or expired token!"
    userNotFound = "User not found!"
    somethingWentWrong = "Woops, something's not quite right, please try again!"
    driverSignupFailed = "Driver signup failed!"
    internalServerErr = "An internal server error occurred!"
    invalidCred = "An invalid credentials were provided!"
    generalTryAgain = "Something went wrong. Please try again!"
    emailAllreadyExists = "Email address already exists!"
    otpExpired = "OTP has expired!"
    userNotVerifiedOrFound = "User has not been verified or not found!"
    errorSavingUser = "Error occurred while saving the user!"
    invalidImageType = "Invalid image type!"
    otpGenerationFailed = "Error occurred while generating OTP!"
    errGeneratingRes = "Error occurred while generating the response!"
    driverNotFound = "Driver not found!"
    vehicleNotFound = "Vehicle not found for the given driver!"
    driverVehicleAlreadyExists = "Driver vehicle already exists!"
    pwdLengthNotMatch = "password must be at least 8 characters long"
    invalidMobileNumber = "Invalid mobile number format. Please provide a valid number with correct length."
    allFieldsRequired =  "All password fields are required."
    pwdNotMatch = "New password and confirm password do not match."
    oldPwdIncorrect = "Old password is incorrect."
    failedToUpdatePwd = "Failed to update password."
    invalidPlanName = "Invalid plan name!"
    planAlreadyExists = "Plan already exists for the driver!"
    noNearbyDriversFound = "No drivers available in your area. Please try again later."
    notificationFailed = "Failed to send notification to drivers."
    rideOrDriverNotFound = "Ride or driver not found with the provided details."
    rideAlreadyAccepted = "Ride has already been accepted by another driver."
    failedtoAccept = "Failed to accept the ride. Please try again later."
    rideNotAccepted = "Ride has not been accepted by any driver yet."
    invalidRideStatus =  "Invalid status transition."
    rideAlreadyAssigned = "Ride already assigned to another driver."
    rideNotFound = "Ride not found with the provided ID."
    rideAlreadyCompletedOrCancelled = "Ride has already been completed or cancelled."
    userOrDriverNotFound = "User or driver not found with the provided details."
    otpExpiredOrInvalid = "OTP is either expired or invalid."


